spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_rest_spring_udemy
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

